### ISSUE TITLE
"Do more" with the title

### ISSUE THREAD

**Issue by dbdness** [KIMB0/ufo-blog-entry#10]
Kasper mentioned that he likes our idea with the title. The way we quote Mongo is good, but we don't leave enough focus on that. This should be changed a bit.

**Comment by Nordalf** [comment]
Tilføjet under "So what now?" : 

_For every software tool out in the world, it can make you 2x more productive, if, and only if, you understand how it works. This means; you've to dig down in the documentation and understand the care concepts of the tool. The more you know the tool, the more effective you will be in your daily worklife. MongoDB didn't made us 2x more productive, because we didn't understood the core concepts and didn't knew about tweaking the configurations of MongoDB to get it to do, what we wanted it to do. Somethings could've been avoided in our case, if we were more educated._

Hvis det er okay, så tilføjes det og vi lukker issued

**Comment by dbdness** [comment]
Jeg kan lide det. Det kunne også være fedt at introducere det i abstracted, men der må bare ikke være alt for mange unødvendige detaljer der. Til trods for at det interesserer læseren. Jeg synes vi skal beholde hvad du har lavet 👍
